# Generated by Django 3.1.6 on 2021-02-08 16:26

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210204_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='uuid',
            field=models.UUIDField(default=core.utils.generate_uuid),
        ),
        migrations.AddField(
            model_name='test',
            name='write_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
