# Generated by Django 3.1.6 on 2021-02-08 16:46

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210208_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='uuid',
            field=models.UUIDField(db_index=True, default=core.utils.generate_uuid),
        ),
    ]
