# Generated by Django 3.1.6 on 2021-02-08 18:33

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_test_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='uuid',
            field=models.UUIDField(db_index=True, default=core.utils.generate_uuid, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='write_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
