# Generated by Django 3.1.6 on 2021-02-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210211_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='write_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
