# Generated by Django 3.1.6 on 2021-02-24 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210222_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
