# Generated by Django 3.1.6 on 2021-08-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210224_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_auth_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
